version: "3"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NETWORK}

services:
  mailserver:
    image: mail
    restart: always
    container_name: mailserver
    domainname: ${DOMAINNAME}
    hostname: ${HOSTNAME}
    ports:
      - "25:25"
 #     - "${ROUNDCUBE_PORT}:80"
      - "80:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "993:993"
      - "995:995"
    env_file:
      - .env
    volumes:
      - ./data/vmail:/var/vmail
      - ./data/log:/var/log
      - ./data/roundcube/logs:/var/www/mail.domic.com/html/logs

    networks:
      net:
